name: Simplify Rules

on:
  push:
    paths:
      - 'rules/Prodcust.list'
      - 'simplify_rule.py'

jobs:
  run-simplify-rule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Run simplify_rule.py
        run: python simplify_rule.py
        
      - name: Commit simplified rules
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add rules/Prodcust.simplified.list
          git commit -m "Auto: update simplified rules"
          git push
